app:
  image:
    path: /Users/darakozuk/Desktop/spring/images

open:
  api:
    authorizationUrl: http://localhost:8080/oauth2/authorization/google
    tokenUrl: https://www.googleapis.com/oauth2/v4/token

springdoc:
  swagger-ui:
    oauth:
      client-id: 621311263911-ad1dntboocualebe057f01p7vsrf8gsi.apps.googleusercontent.com
      client-secret: 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
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 621311263911-ad1dntboocualebe057f01p7vsrf8gsi.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile
  messages:
    basename: messages
    fallback-to-system-locale: false
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        current_session_context_class: thread
        hbm2ddl.auto: validate
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false

logging:
  file:
    name: spring-starter.log
    path: /
  level:
    root: info



